# -*- coding: utf-8 -*-
"""final_subscriber

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Vci8pSu1ImITf7ns5w5FGIGb0ozSaic
"""

#!/usr/bin/env python3

import rospy
from std_msgs.msg import String
def callback(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)
def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("std_id", String, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()