# -*- coding: utf-8 -*-
"""final_publish

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yg_h8SoGBw8lu9sjuXuNUEd_LjI6zZeX
"""

#!/usr/bin/env python3
import rospy
from std_msgs.msg import String
def talker():
    pub = rospy.Publisher('std_id', String, queue_size=10)
    rospy.init_node('talker', anonymous=True)
    rate = rospy.Rate(10) # 10hz
    while not rospy.is_shutdown():
        hello_str = "6352500773" % rospy.get_time()
        rospy.loginfo(hello_str)
        pub.publish(hello_str)
        rate.sleep()
if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass